/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestRouteImport } from './routes/request'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as IntelIndexRouteImport } from './routes/intel.index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as ProvidersProviderIdRouteImport } from './routes/providers.$providerId'
import { Route as ProviderDashboardRouteImport } from './routes/provider.dashboard'
import { Route as PoliciesCancellationRouteImport } from './routes/policies.cancellation'
import { Route as OnboardingProviderRouteImport } from './routes/onboarding.provider'
import { Route as OnboardingClientRouteImport } from './routes/onboarding/client'
import { Route as IntelVenuesRouteImport } from './routes/intel.venues'
import { Route as IntelRatesRouteImport } from './routes/intel.rates'
import { Route as IntelEventsRouteImport } from './routes/intel.events'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as BookProviderIdRouteImport } from './routes/book.$providerId'
import { Route as AdminScraperRouteImport } from './routes/admin.scraper'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminIntelRouteImport } from './routes/admin.intel'
import { Route as AdminConciergeRouteImport } from './routes/admin.concierge'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelIndexRoute = IntelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntelRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersProviderIdRoute = ProvidersProviderIdRouteImport.update({
  id: '/providers/$providerId',
  path: '/providers/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderDashboardRoute = ProviderDashboardRouteImport.update({
  id: '/provider/dashboard',
  path: '/provider/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesCancellationRoute = PoliciesCancellationRouteImport.update({
  id: '/policies/cancellation',
  path: '/policies/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProviderRoute = OnboardingProviderRouteImport.update({
  id: '/onboarding/provider',
  path: '/onboarding/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingClientRoute = OnboardingClientRouteImport.update({
  id: '/onboarding/client',
  path: '/onboarding/client',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelVenuesRoute = IntelVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => IntelRoute,
} as any)
const IntelRatesRoute = IntelRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => IntelRoute,
} as any)
const IntelEventsRoute = IntelEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => IntelRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookProviderIdRoute = BookProviderIdRouteImport.update({
  id: '/book/$providerId',
  path: '/book/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScraperRoute = AdminScraperRouteImport.update({
  id: '/scraper',
  path: '/scraper',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntelRoute = AdminIntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConciergeRoute = AdminConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intel': typeof IntelRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/concierge': typeof AdminConciergeRoute
  '/admin/intel': typeof AdminIntelRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/scraper': typeof AdminScraperRoute
  '/book/$providerId': typeof BookProviderIdRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/intel/events': typeof IntelEventsRoute
  '/intel/rates': typeof IntelRatesRoute
  '/intel/venues': typeof IntelVenuesRoute
  '/onboarding/client': typeof OnboardingClientRoute
  '/onboarding/provider': typeof OnboardingProviderRoute
  '/policies/cancellation': typeof PoliciesCancellationRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/intel/': typeof IntelIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/concierge': typeof AdminConciergeRoute
  '/admin/intel': typeof AdminIntelRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/scraper': typeof AdminScraperRoute
  '/book/$providerId': typeof BookProviderIdRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/intel/events': typeof IntelEventsRoute
  '/intel/rates': typeof IntelRatesRoute
  '/intel/venues': typeof IntelVenuesRoute
  '/onboarding/client': typeof OnboardingClientRoute
  '/onboarding/provider': typeof OnboardingProviderRoute
  '/policies/cancellation': typeof PoliciesCancellationRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/intel': typeof IntelIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intel': typeof IntelRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/concierge': typeof AdminConciergeRoute
  '/admin/intel': typeof AdminIntelRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/scraper': typeof AdminScraperRoute
  '/book/$providerId': typeof BookProviderIdRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/intel/events': typeof IntelEventsRoute
  '/intel/rates': typeof IntelRatesRoute
  '/intel/venues': typeof IntelVenuesRoute
  '/onboarding/client': typeof OnboardingClientRoute
  '/onboarding/provider': typeof OnboardingProviderRoute
  '/policies/cancellation': typeof PoliciesCancellationRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/intel/': typeof IntelIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/intel'
    | '/login'
    | '/privacy'
    | '/request'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/terms'
    | '/admin/concierge'
    | '/admin/intel'
    | '/admin/revenue'
    | '/admin/scraper'
    | '/book/$providerId'
    | '/categories/$slug'
    | '/intel/events'
    | '/intel/rates'
    | '/intel/venues'
    | '/onboarding/client'
    | '/onboarding/provider'
    | '/policies/cancellation'
    | '/provider/dashboard'
    | '/providers/$providerId'
    | '/categories/'
    | '/intel/'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/request'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/terms'
    | '/admin/concierge'
    | '/admin/intel'
    | '/admin/revenue'
    | '/admin/scraper'
    | '/book/$providerId'
    | '/categories/$slug'
    | '/intel/events'
    | '/intel/rates'
    | '/intel/venues'
    | '/onboarding/client'
    | '/onboarding/provider'
    | '/policies/cancellation'
    | '/provider/dashboard'
    | '/providers/$providerId'
    | '/categories'
    | '/intel'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/intel'
    | '/login'
    | '/privacy'
    | '/request'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/terms'
    | '/admin/concierge'
    | '/admin/intel'
    | '/admin/revenue'
    | '/admin/scraper'
    | '/book/$providerId'
    | '/categories/$slug'
    | '/intel/events'
    | '/intel/rates'
    | '/intel/venues'
    | '/onboarding/client'
    | '/onboarding/provider'
    | '/policies/cancellation'
    | '/provider/dashboard'
    | '/providers/$providerId'
    | '/categories/'
    | '/intel/'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IntelRoute: typeof IntelRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RequestRoute: typeof RequestRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  BookProviderIdRoute: typeof BookProviderIdRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  OnboardingClientRoute: typeof OnboardingClientRoute
  OnboardingProviderRoute: typeof OnboardingProviderRoute
  PoliciesCancellationRoute: typeof PoliciesCancellationRoute
  ProviderDashboardRoute: typeof ProviderDashboardRoute
  ProvidersProviderIdRoute: typeof ProvidersProviderIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel/': {
      id: '/intel/'
      path: '/'
      fullPath: '/intel/'
      preLoaderRoute: typeof IntelIndexRouteImport
      parentRoute: typeof IntelRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$providerId': {
      id: '/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof ProvidersProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/dashboard': {
      id: '/provider/dashboard'
      path: '/provider/dashboard'
      fullPath: '/provider/dashboard'
      preLoaderRoute: typeof ProviderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/cancellation': {
      id: '/policies/cancellation'
      path: '/policies/cancellation'
      fullPath: '/policies/cancellation'
      preLoaderRoute: typeof PoliciesCancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/provider': {
      id: '/onboarding/provider'
      path: '/onboarding/provider'
      fullPath: '/onboarding/provider'
      preLoaderRoute: typeof OnboardingProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/client': {
      id: '/onboarding/client'
      path: '/onboarding/client'
      fullPath: '/onboarding/client'
      preLoaderRoute: typeof OnboardingClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel/venues': {
      id: '/intel/venues'
      path: '/venues'
      fullPath: '/intel/venues'
      preLoaderRoute: typeof IntelVenuesRouteImport
      parentRoute: typeof IntelRoute
    }
    '/intel/rates': {
      id: '/intel/rates'
      path: '/rates'
      fullPath: '/intel/rates'
      preLoaderRoute: typeof IntelRatesRouteImport
      parentRoute: typeof IntelRoute
    }
    '/intel/events': {
      id: '/intel/events'
      path: '/events'
      fullPath: '/intel/events'
      preLoaderRoute: typeof IntelEventsRouteImport
      parentRoute: typeof IntelRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$providerId': {
      id: '/book/$providerId'
      path: '/book/$providerId'
      fullPath: '/book/$providerId'
      preLoaderRoute: typeof BookProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scraper': {
      id: '/admin/scraper'
      path: '/scraper'
      fullPath: '/admin/scraper'
      preLoaderRoute: typeof AdminScraperRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/intel': {
      id: '/admin/intel'
      path: '/intel'
      fullPath: '/admin/intel'
      preLoaderRoute: typeof AdminIntelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/concierge': {
      id: '/admin/concierge'
      path: '/concierge'
      fullPath: '/admin/concierge'
      preLoaderRoute: typeof AdminConciergeRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConciergeRoute: typeof AdminConciergeRoute
  AdminIntelRoute: typeof AdminIntelRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminScraperRoute: typeof AdminScraperRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConciergeRoute: AdminConciergeRoute,
  AdminIntelRoute: AdminIntelRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminScraperRoute: AdminScraperRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface IntelRouteChildren {
  IntelEventsRoute: typeof IntelEventsRoute
  IntelRatesRoute: typeof IntelRatesRoute
  IntelVenuesRoute: typeof IntelVenuesRoute
  IntelIndexRoute: typeof IntelIndexRoute
}

const IntelRouteChildren: IntelRouteChildren = {
  IntelEventsRoute: IntelEventsRoute,
  IntelRatesRoute: IntelRatesRoute,
  IntelVenuesRoute: IntelVenuesRoute,
  IntelIndexRoute: IntelIndexRoute,
}

const IntelRouteWithChildren = IntelRoute._addFileChildren(IntelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IntelRoute: IntelRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RequestRoute: RequestRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  BookProviderIdRoute: BookProviderIdRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  OnboardingClientRoute: OnboardingClientRoute,
  OnboardingProviderRoute: OnboardingProviderRoute,
  PoliciesCancellationRoute: PoliciesCancellationRoute,
  ProviderDashboardRoute: ProviderDashboardRoute,
  ProvidersProviderIdRoute: ProvidersProviderIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
