/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RequestRouteImport } from './routes/request'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as ProvidersProviderIdRouteImport } from './routes/providers.$providerId'
import { Route as ProviderDashboardRouteImport } from './routes/provider.dashboard'
import { Route as PoliciesCancellationRouteImport } from './routes/policies.cancellation'
import { Route as OnboardingProviderRouteImport } from './routes/onboarding.provider'
import { Route as OnboardingClientRouteImport } from './routes/onboarding/client'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as BookProviderIdRouteImport } from './routes/book.$providerId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersProviderIdRoute = ProvidersProviderIdRouteImport.update({
  id: '/providers/$providerId',
  path: '/providers/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderDashboardRoute = ProviderDashboardRouteImport.update({
  id: '/provider/dashboard',
  path: '/provider/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesCancellationRoute = PoliciesCancellationRouteImport.update({
  id: '/policies/cancellation',
  path: '/policies/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProviderRoute = OnboardingProviderRouteImport.update({
  id: '/onboarding/provider',
  path: '/onboarding/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingClientRoute = OnboardingClientRouteImport.update({
  id: '/onboarding/client',
  path: '/onboarding/client',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookProviderIdRoute = BookProviderIdRouteImport.update({
  id: '/book/$providerId',
  path: '/book/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/book/$providerId': typeof BookProviderIdRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/onboarding/client': typeof OnboardingClientRoute
  '/onboarding/provider': typeof OnboardingProviderRoute
  '/policies/cancellation': typeof PoliciesCancellationRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/book/$providerId': typeof BookProviderIdRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/onboarding/client': typeof OnboardingClientRoute
  '/onboarding/provider': typeof OnboardingProviderRoute
  '/policies/cancellation': typeof PoliciesCancellationRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/book/$providerId': typeof BookProviderIdRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/onboarding/client': typeof OnboardingClientRoute
  '/onboarding/provider': typeof OnboardingProviderRoute
  '/policies/cancellation': typeof PoliciesCancellationRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/request'
    | '/search'
    | '/signup'
    | '/terms'
    | '/book/$providerId'
    | '/categories/$slug'
    | '/onboarding/client'
    | '/onboarding/provider'
    | '/policies/cancellation'
    | '/provider/dashboard'
    | '/providers/$providerId'
    | '/categories/'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/request'
    | '/search'
    | '/signup'
    | '/terms'
    | '/book/$providerId'
    | '/categories/$slug'
    | '/onboarding/client'
    | '/onboarding/provider'
    | '/policies/cancellation'
    | '/provider/dashboard'
    | '/providers/$providerId'
    | '/categories'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/request'
    | '/search'
    | '/signup'
    | '/terms'
    | '/book/$providerId'
    | '/categories/$slug'
    | '/onboarding/client'
    | '/onboarding/provider'
    | '/policies/cancellation'
    | '/provider/dashboard'
    | '/providers/$providerId'
    | '/categories/'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RequestRoute: typeof RequestRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  BookProviderIdRoute: typeof BookProviderIdRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  OnboardingClientRoute: typeof OnboardingClientRoute
  OnboardingProviderRoute: typeof OnboardingProviderRoute
  PoliciesCancellationRoute: typeof PoliciesCancellationRoute
  ProviderDashboardRoute: typeof ProviderDashboardRoute
  ProvidersProviderIdRoute: typeof ProvidersProviderIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$providerId': {
      id: '/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof ProvidersProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/dashboard': {
      id: '/provider/dashboard'
      path: '/provider/dashboard'
      fullPath: '/provider/dashboard'
      preLoaderRoute: typeof ProviderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/cancellation': {
      id: '/policies/cancellation'
      path: '/policies/cancellation'
      fullPath: '/policies/cancellation'
      preLoaderRoute: typeof PoliciesCancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/provider': {
      id: '/onboarding/provider'
      path: '/onboarding/provider'
      fullPath: '/onboarding/provider'
      preLoaderRoute: typeof OnboardingProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/client': {
      id: '/onboarding/client'
      path: '/onboarding/client'
      fullPath: '/onboarding/client'
      preLoaderRoute: typeof OnboardingClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$providerId': {
      id: '/book/$providerId'
      path: '/book/$providerId'
      fullPath: '/book/$providerId'
      preLoaderRoute: typeof BookProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RequestRoute: RequestRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  BookProviderIdRoute: BookProviderIdRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  OnboardingClientRoute: OnboardingClientRoute,
  OnboardingProviderRoute: OnboardingProviderRoute,
  PoliciesCancellationRoute: PoliciesCancellationRoute,
  ProviderDashboardRoute: ProviderDashboardRoute,
  ProvidersProviderIdRoute: ProvidersProviderIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
